# Generated by Django 5.1.1 on 2024-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
